# services:
#   app:
#     image: mytodo:latest
#     environment:
#       - NEXT_PUBLIC_API_URL=https://api.example.com
#       - DATABASE_URL=postgresql://user:pass@db:5432/db
#       - NEXTAUTH_SECRET=your-secret-key
#     env_file:
#       - ./env.production  # 如果文件存在且不被.dockerignore排除
#     ports:
#       - "3000:3000"
#     deploy:
#       resources:
#         limits:
#           memory: 512M
#           cpus: '0.5'
#         reservations:
#           memory: 256M
#           cpus: '0.25'
#     restart: unless-stopped

# 推荐的 docker-compose.yml
version: '3.8'
services:
  app:
    image: mytodo:latest
    environment:
      # 公开环境变量（客户端可访问）
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # 私有环境变量（服务器端使用）
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    env_file:
      - .env.production  # 如果存在且不被排除
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
